name: Generate CV Site  

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - run: echo ${{github.ref}}
    - uses: actions/checkout@v4

    - name: Install xstlproc
      run: sudo apt-get -y install xsltproc

    - name: Generate site 
      run: . ./generate-site.sh 

    - name: Upload calc artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: index-file
        path: index.html
    
  deploy-dockerhub:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Download index file 
      uses: actions/download-artifact@v4
      with:
        name: index-file
        path: index.html

    - name: Make sure the index.html exists 
      run: (cd .; ls -alrt; cat index.html;)

      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/funcv:latest
        build-args: |
            root_path=${{ secrets.ROOT_PATH }}
